### ISSUE TITLE
Trajectories.txt file contains the gt poses ?

### ISSUE THREAD

**Issue by alexs7** [microsoft/lamar-benchmark#10]
Hello, for the HGE data folder, the map folder contains the mapping data to build the initial model.
There is a `trajectories.txt` file, that contain camera poses. Are those poses the ground truth data for the map model ?
Are they also in metric units ?

**Comment by Skydes** [comment]
- For the mapping folder, the file `trajectories.txt` contains the refined (metric) poses obtained using our GT pipeline (in camera-to-world format).
- For the queries, the file `trajectories.txt` contains the raw on-device odometry poses (which are not aligned to the global frame nor refined). The GT poses for queries were kept private. However, we released the GT poses for some validation sequences in `*_val/proc/alignment_trajectories.txt`.

**Comment by alexs7** [comment]
Ok thanks! Do the poses follow an inverse convention from COLMAP's ?
In COLMAP docs they say: ["The reconstructed pose of an image is specified as the projection from world to the camera coordinate system"](https://colmap.github.io/format.html#images-txt).

**Comment by Skydes** [comment]
Yes, the poses here follow the inverse convention - they transform points from camera to world frame.

**Comment by alexs7** [comment]
Ok thanks!!
