### ISSUE TITLE
3D Laser Scans for Mapping Session

### ISSUE THREAD

**Issue by lahavlipson** [microsoft/lamar-benchmark#11]
Hello,

I noticed that the 3D laser scans used to obtain the ground-truth mapping poses weren't included in the evaluation data.

Is there a plan to release these database scans (similar to InLoc), or are we expected to reconstruct a 3D map by running a mapping algorithm using the provided mapping images and poses (e.g. COLMAP MVS)?

Thanks for the clarification.

**Comment by Skydes** [comment]
Hi Lahav,

Our setup and data for evaluating localization and mapping indeed assumes that 3D maps are built solely using sensors embedded by AR devices (images, IMU, radios). We evaluated lidar maps in the paper but this is not part of the benchmark for now.

We do plan to release all raw data, including reference lidar scans and on-device depth maps, but we are still working on it (it's a massive scale). Feel free to let us know if you have specific preferences or use cases in mind.

**Comment by lahavlipson** [comment]
Sounds good, looking forward to the full raw data release.

Closing this issue now.
