### ISSUE TITLE
Images in the current evaluation

### ISSUE THREAD

**Issue by lahavlipson** [microsoft/lamar-benchmark#14]
At some timesteps in the hololens sequences there are only images for a subset of the cameras (hetlf, hetll, hetrf, hetrr). For these timesteps, are there additional images that will eventually be released?

Also, the paper says that the query images are sampled every 1s/1m/20°, although I assume the sequences were recorded at a higher frame-rate. Will the full video sequences eventually be released? These intermediate frames could help localization during fast motion, even if they aren't used for evaluation.

**Comment by Skydes** [comment]
1. For performance reasons, the HoloLens does not record all cameras at each timestamp, which indeed results in partial rigs. We might manage to turn this off in the future, but existing sequences can only be used as is.
2. The original sequences are indeed recorded at about 30 FPS for HoloLens and 5-10 FPS for the phones. Yes, the full data release will contain the images discarded by the keyframing.

**Comment by lahavlipson** [comment]
Thank you for the clarification, closing this issue now.

**Comment by C-H-Chien** [comment]
Hi! I am curious what the "performance reasons" are, since for some tasks the synchronization of four cameras of the same rig is critical.
