### ISSUE TITLE
Access to point cloud data

### ISSUE THREAD

**Issue by jeandsp** [microsoft/lamar-benchmark#16]
Hello,

First of congrats for the development of this benchmark, really impressive !
I was wandering, do you have a timeline to roughly know when we could get access to the ground truth  points clouds data ?

Thanks.

**Comment by sarlinpe** [comment]
Apologies for the late reply. The raw data has now been released (https://github.com/microsoft/lamar-benchmark/commit/cd182f1a29dbcea80b3e3286b68aa7ab843d52c7) and can be accessed at the same link as previously or by filling in the form [linked on our website](https://lamar.ethz.ch/). Feel free to open a new issue in case you face trouble using the data.
