### ISSUE TITLE
Paper link

### ISSUE THREAD

**Issue by rann1018** [microsoft/lamar-benchmark#2]
Hi Sarlin,

Very excited to see your new work!
And could you please publish a link to this paper?

Thanks a lot for your attention.

**Comment by Skydes** [comment]
Thank you for your interest. As ECCV forces us to publish the code so early, more details on the paper and benchmark will be released only later in due time. Please subscribe to [this issue](https://github.com/microsoft/lamar-benchmark/issues/4) to receive notifications of the full release.

**Comment by Skydes** [comment]
We now have a project page with the paper and video: https://lamar.ethz.ch/ The full code will be released very soon.
