### ISSUE TITLE
About 3D Models

### ISSUE THREAD

**Issue by LikeRain0** [microsoft/lamar-benchmark#27]
Hello, I'm sorry to bother you.
I would like to ask if your dataset can generate a 3D point cloud model of the scene. If so, how do I operate?

**Comment by sarlinpe** [comment]
Apologies for the late reply. The raw data, which includes the 3D lidar point clouds, has now been released (https://github.com/microsoft/lamar-benchmark/commit/cd182f1a29dbcea80b3e3286b68aa7ab843d52c7) and can be accessed at the same link as previously or by filling in the form [linked on our website](https://lamar.ethz.ch/). Feel free to open a new issue in case you face trouble using the data.
