### ISSUE TITLE
looking forward to the paper

### ISSUE THREAD

**Issue by cuge1995** [microsoft/lamar-benchmark#3]

**Comment by Skydes** [comment]
Thank you for your interest. As ECCV forces us to publish the code so early, more details on the paper and benchmark will be released only later in due time. Please subscribe to [this issue](https://github.com/microsoft/lamar-benchmark/issues/4) to receive notifications of the full release.

**Comment by Skydes** [comment]
We now have a project page with the paper and video: https://lamar.ethz.ch/ The full code will be released very soon.

**Comment by cuge1995** [comment]
I have added this benchmark to the [Deep-SLAM](https://github.com/cuge1995/Deep-SLAM) repo, and I hope this work will be influential work in this field.
