### ISSUE TITLE
Access to gyroscope.txt and accelerometer.txt of public released dataset

### ISSUE THREAD

**Issue by qimaqi** [microsoft/lamar-benchmark#32]
Hello thanks for the amazing work.
I download the publicly released dataset but find even though in the repo it provides the IOS app for recording the gyroscope and accelerometer but I can not find it in the public dataset. Will it be accessible in the future?

**Comment by Skydes** [comment]
Hello! Yes we are actively working on releasing the entirety of the dataset, including the raw IMU data - it's just taking a bit longer than initially expected. We will make an announcement when this happens.

**Comment by sarlinpe** [comment]
Apologies for the late reply. The raw data, which includes the IMU data, has now been released (https://github.com/microsoft/lamar-benchmark/commit/cd182f1a29dbcea80b3e3286b68aa7ab843d52c7) and can be accessed at the same link as previously or by filling in the form [linked on our website](https://lamar.ethz.ch/). Feel free to open a new issue in case you face trouble using the data.
