### ISSUE TITLE
Question about the coordinates of LaMaR dataset

### ISSUE THREAD

**Issue by Yukun66** [microsoft/lamar-benchmark#37]
Thanks for your perfect dataset! I have a question about the coordinate of the dataset. According to your ground truth pose in the " HGE", "sessions",  "map", and "ios_2022-01-25_14.34.24_002" scene, I draw the camera in open3D, it looks like all the cameras are looking at UP. While I draw these cameras after I run colmap, the direction looks forward correctly. So I'm wondering what the coordinate of the ground truth pose is. I can't find the definition in the paper and git repo. Thanks!
Ground truth poses looks like this:
![Screenshot from 2023-05-27 15-17-08](https://github.com/microsoft/lamar-benchmark/assets/71137799/66fc1639-1260-4b02-9d76-59b70b0b152b)
Colmap poses looks like this:
![Screenshot from 2023-05-27 15-25-09](https://github.com/microsoft/lamar-benchmark/assets/71137799/c0133c21-a167-47cb-9b85-ac5395a1efdf)

**Comment by Skydes** [comment]
According to the [documentation of the format](https://github.com/microsoft/lamar-benchmark/blob/main/CAPTURE.md):
> `rigs.txt` contains camera-to-rig transformations and `trajectories.txt` contains sensor-to-world transformations.

This means that each provided pose transforms a point in the camera frame to the world frame. COLMAP uses the inverse, world-to-sensor convention.

**Comment by Yukun66** [comment]
> According to the [documentation of the format](https://github.com/microsoft/lamar-benchmark/blob/main/CAPTURE.md):
> 
> > `rigs.txt` contains camera-to-rig transformations and `trajectories.txt` contains sensor-to-world transformations.
> 
> This means that each provided pose transforms a point in the camera frame to the world frame. COLMAP uses the inverse, world-to-sensor convention.

Thanks for your reply, Sarlin. I've checked this doc and the `rigs.txt` and `trajectories.txt`, and it seems like only 4 Hololens cameras have the poses in `rigs.txt`, while iPhone cameras don't. So I'm wondering if the poses in `trajectories.txt` is the iPhone camera poses? So it doesn't need the poses from the sensor to rig? Because according to the >https://github.com/naver/kapture/blob/main/kapture_format.adoc#2--sensors
the trajectories.txt is the transform from world to devices. Thanks!
