### ISSUE TITLE
Raw depth data

### ISSUE THREAD

**Issue by yuxuan1206** [microsoft/lamar-benchmark#39]
Very good work! May I ask if the raw depth data of the device is not yet available in the current release?

**Comment by sarlinpe** [comment]
Apologies for the late reply. The raw data, which includes the depth maps, has now been released (https://github.com/microsoft/lamar-benchmark/commit/cd182f1a29dbcea80b3e3286b68aa7ab843d52c7) and can be accessed at the same link as previously or by filling in the form [linked on our website](https://lamar.ethz.ch/). Feel free to open a new issue in case you face trouble using the data.
