### ISSUE TITLE
Question about GNC: where was it implemented?

### ISSUE THREAD

**Issue by TxT1212** [microsoft/lamar-benchmark#48]
In function optimize_sequence_pose_graph_gnc, the comment says "Apply Graduated Non-Convexity (GNC) to the robust cost of the localization prior. Loose implementation of the paper: Graduated Non-Convexity for Robust Spatial Perception: From Non-Minimal Solvers to Global Outlier Rejection". I'm curious if you actually implemented the GNC. It seems like you only updated mu in the while loop, but didn't actually use it in graph optimization.

**Comment by sarlinpe** [comment]
We apply GNC to the localization edges of the pose graph (unary factors) because they are likely to be contaminated by outliers (incorrect loop closures). The remaining edges are derived from the on-device VIO/SLAM and are fairly reliable (but have drift) so they don't required additional robustness.

**Comment by TxT1212** [comment]
in the paper, there is a step to update the weight of each residual error. I didn't find the weight.

**Comment by sarlinpe** [comment]
We solve a factor graph with robust loss so we don't need to explicitly weight the optimization, it's handled by gtsam, which simply weights the contribution of each residual.

**Comment by TxT1212** [comment]
Does lamar use gtsam? I thought only ceres is used. What is the relationship between pyceres and gtsam?

**Comment by sarlinpe** [comment]
Of course I meant pyceres, sorry :)

**Comment by TxT1212** [comment]
I see. Thanks for your reply.
