### ISSUE TITLE
Question about evaluation results for test queries

### ISSUE THREAD

**Issue by oscarpang** [microsoft/lamar-benchmark#53]
Hi there,

I checked the default `queries.txt` in the capture folder (e.g. `LIN`). It contains ~1000 queries. I think it's a subset of the images in the `raw_data` folders. 

In the benchmark submission, would you only accept poses for images in the `queries.txt` or you also accept poses for other images that are not included in `queries.txt` but exists in the `query_phone`?

Thanks!

**Comment by oscarpang** [comment]
Gentle ping.

**Comment by sarlinpe** [comment]
Apologies for the late reply. The evaluation looks for poses poses only of queries listed in `queries.txt`. Poses of other images are simply ignored:
https://github.com/microsoft/lamar-benchmark/blob/147c9a4b40c49f9f6e48854996fc20f4d531d9c6/lamar/tasks/pose_estimation.py#L134-L136
https://github.com/microsoft/lamar-benchmark/blob/147c9a4b40c49f9f6e48854996fc20f4d531d9c6/lamar/utils/localization.py#L131-L140

**Comment by oscarpang** [comment]
Thanks for the reply. I understand that the run.py only looks at the queries in the `queries.txt`. 

I'm interested in running a continuous pose estimation for images under the `query_phone/image` folder. I wonder if the benchmark submission can evaluate those images other than the ones in `queries.txt` and provide the error/recall? Or the benchmark submission only supports the queries in the `queries.txt`.

Thanks!

**Comment by sarlinpe** [comment]
Queries were selected among keyframes - images whose ground truth poses were also constrained with localization terms. In practice we didn't compute ground truth poses for non-keyframe images. So we have such poses for more images than the queries but not for all images.

**Comment by oscarpang** [comment]
Thanks! I think my previous question is mis-worded. I actually wonder about the gt for __keyframes__ other than the ones included in `queries.txt`. 

A concrete example is that `LIN/sessions/query_phone/raw_data/ios_2021-06-02_11.04.35_000` has around 80 images, and the `queries.txt` only has 10 images for the sequence `ios_2021-06-02_11.04.35_000`. My question is that if I submit results for all the 80 images, would I get error estimation for these 80 images, or just the 10 images?

**Comment by sarlinpe** [comment]
Just for the 10 images.

> The evaluation looks for poses poses only of queries listed in queries.txt

**Comment by oscarpang** [comment]
Thanks!
