### ISSUE TITLE
Wrong arguments in pycolmap.absolute_pose_estimation

### ISSUE THREAD

**Issue by serizba** [microsoft/lamar-benchmark#67]
Hi! 

Thanks for this great benchmark. I'm trying to run the validation on a Docker container built using the provided Dockerfile.

Command:
```
python -m lamar.run \
	--scene CAB --ref_id map --query_id query_val_phone \
	--retrieval fusion --feature superpoint --matcher superglue
```

However, it fails when computing absolute_pose_estimation [here](https://github.com/microsoft/lamar-benchmark/blob/0846a07a9575fa96cfee616598562852211a5723/lamar/utils/localization.py#L72). The function is being called with points2D, points3D, camera, max_error and return covariance. However, in pycolmap 0.6.0, the function expects a different set of arguments (see [here](https://github.com/colmap/colmap/blob/eaffee32295ac211d87273a891ce69a4414934a7/src/pycolmap/estimators/absolute_pose.cc#L137)). Also the returned dictionary is different from the expected. 

I don't know if this is a mismatch of version of pycolmap, but if so, what is the required pycolmap version?

Thanks in advance

**Comment by sarlinpe** [comment]
Hi there,
The README mentions that LaMAR needs hloc 1.4 and COLMAP 3.8, which both correspond to pycolmap v0.4.0. I will make this more clear in the setup instructions - sorry about this. We're still doing major changes in (py)COLMAP so we haven't yet updated the LaMAR toolkit to >v0.4.0.

**Comment by serizba** [comment]
This fixes it, thanks!
