### ISSUE TITLE
gt pose error

### ISSUE THREAD

**Issue by zhizunhu** [microsoft/lamar-benchmark#9]
Hello, I would like to use your great benchmark to test my program, But I just find some errors in GT pose. Like that:
    I think that trajectories.txt in each folder is the GT post, right? But poses in 'query_val_phone' is not the same as poses in 'map' even though they are the same images. So trajectories.txt in  'query_val_phone' folder is not GT pose? 
<img width="1032" alt="截屏2022-11-29 22 20 23" src="https://user-images.githubusercontent.com/55144462/204554053-24ddb450-94dd-4f09-9907-db798e2f17d7.png">
<img width="1026" alt="截屏2022-11-29 22 20 58" src="https://user-images.githubusercontent.com/55144462/204554204-1b805cf0-30d0-4452-bb16-6aed1175f9fd.png">

**Comment by Skydes** [comment]
- For the mapping folder, the file `trajectories.txt` contains the refined (metric) poses obtained using our GT pipeline (in camera-to-world format).
- For the queries, the file `trajectories.txt` contains the raw on-device odometry poses (which are not aligned to the global frame nor refined). The GT poses for the validation sequences are in `*_val/proc/alignment_trajectories.txt`.

As for the overlap between mapping and validation sequences: we are looking into it.
